name: run main.py

on:
  push:
    branches:
      - '*'
      - '!main'   # excludes master
  pull_request:
    types: [opened, reopened]
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          branch: ${{ github.ref }}
        if: github.event_name != 'pull_request'
      - run: echo "Pull Request ${PR_NUMBER}"
        env:
          PR_NUMBER: ${{ steps.find-pull-request.outputs.number }}

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
          PR_NUMBER: ${{ steps.find-pull-request.outputs.number }}
          BRANCH: ${{ github.ref }}
          REPO_NAME: ${{ github.repository }}
        run: python main.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
